 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}:$COMMIT_SHA', '.']
 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - '${_SERVICE_NAME}'
   - '--image'
   - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}:$COMMIT_SHA'
   - '--region'
   - '${_LOCATION}'
 images:
 - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}:$COMMIT_SHA'
